/**
 * Generate client/public/sw.js.
 *
 *   npx tsx scripts/buildServiceWorker.ts
 *
 * The cache name carries the pinned MediaPipe checksums, so changing a model
 * invalidates every cached copy of it. Without that, a device keeps serving
 * the old weights forever — the eval and the user would disagree about what
 * was measured, with nothing in the repo having changed. Run this after
 * touching MODEL_SPECS; a test asserts the two stay in step.
 */
import fs from "fs";
import path from "path";
import { MODEL_SPECS } from "../measure/landmarks";

export function cacheName(): string {
  const version = [MODEL_SPECS.landmarker.sha256, MODEL_SPECS.segmenter.sha256]
    .map((s) => s.slice(0, 8))
    .join("-");
  return `aura-${version}`;
}

const SW = `/**
 * Aura service worker — GENERATED by scripts/buildServiceWorker.ts.
 *
 * Do not edit. The cache name is derived from the pinned MediaPipe checksums
 * in measure/landmarks.ts, so a model change invalidates every cached copy.
 */

const CACHE = ${JSON.stringify(cacheName())};

/** Enough to open the app with no network at all. */
const SHELL = ["/", "/index.html", "/manifest.webmanifest", "/icons/icon-192.png"];

/**
 * Large, immutable, expensive to fetch twice: MediaPipe weights, codec WASM,
 * hashed build assets and the product imagery. Cached on first use rather than
 * at install — 20 MB up front would be charged to someone who may never
 * analyse a photo.
 */
function isImmutableAsset(url) {
  return (
    url.hostname === "storage.googleapis.com" ||
    url.pathname.startsWith("/wasm/") ||
    url.pathname.startsWith("/assets/") ||
    url.pathname.startsWith("/icons/") ||
    url.pathname.startsWith("/makeup/") ||
    url.pathname.startsWith("/demo-faces/")
  );
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);

  // Never cache the API. Every response belongs to one photo, and a stale
  // analysis served from disk would be somebody else's result.
  if (url.pathname.startsWith("/api/")) return;

  if (isImmutableAsset(url)) {
    event.respondWith(
      caches.match(request).then(
        (hit) =>
          hit ||
          fetch(request).then((response) => {
            if (response.ok || response.type === "opaque") {
              const copy = response.clone();
              caches.open(CACHE).then((c) => c.put(request, copy));
            }
            return response;
          })
      )
    );
    return;
  }

  // Navigations: network first, cached shell as the fallback. Cache-first here
  // would pin an old build on the device forever.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((c) => c.put("/index.html", copy));
          return response;
        })
        .catch(() => caches.match("/index.html").then((hit) => hit || Response.error()))
    );
  }
});
`;

if (require.main === module) {
  const out = path.join(__dirname, "../client/public/sw.js");
  fs.writeFileSync(out, SW);
  console.log(`wrote ${path.relative(process.cwd(), out)} — cache ${cacheName()}`);
}
