import { jsPDF } from "jspdf";

interface ColorSwatch {
  name: string;
  hex: string;
  note?: string;
  reason?: string;
}

interface AnalysisData {
  season: string;
  confidence: number;
  undertone: string;
  depth: string;
  chroma: string;
  koreanTone: string;
  reasoning: string;
  keyFeatures: Record<string, string>;
  palette: {
    best: ColorSwatch[];
    avoid: ColorSwatch[];
    neutrals: string[];
    metals: { best: string[]; avoid: string[] };
  };
  makeup: Record<string, unknown>;
  wardrobe: Record<string, string>;
  jewelry: Record<string, string>;
  hairColor: Record<string, string>;
  celebrities: { name: string; why: string }[];
  koreanAnalysis: Record<string, string>;
}

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

function isWarmSeason(season: string): boolean {
  return (
    season.toLowerCase().includes("autumn") ||
    season.toLowerCase().includes("spring")
  );
}

export function generatePDF(data: AnalysisData): Buffer {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = 210;
  const pageH = 297;
  const margin = 20;
  const contentW = pageW - margin * 2;

  const warm = isWarmSeason(data.season);
  const bg: [number, number, number] = warm ? [26, 15, 8] : [8, 15, 26];
  const accent: [number, number, number] = warm
    ? [201, 169, 110]
    : [110, 160, 201];
  const textLight: [number, number, number] = warm
    ? [245, 236, 215]
    : [215, 230, 245];
  const textMuted: [number, number, number] = warm
    ? [180, 165, 140]
    : [140, 165, 180];

  function addBackground() {
    doc.setFillColor(...bg);
    doc.rect(0, 0, pageW, pageH, "F");
  }

  function addHeader(title: string, y: number): number {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(...accent);
    doc.text(title, margin, y);
    doc.setDrawColor(...accent);
    doc.setLineWidth(0.5);
    doc.line(margin, y + 2, margin + contentW, y + 2);
    return y + 12;
  }

  function addText(
    text: string,
    x: number,
    y: number,
    maxW: number,
    size = 10,
    color: [number, number, number] = textLight
  ): number {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, maxW);
    doc.text(lines, x, y);
    return y + lines.length * (size * 0.45) + 2;
  }

  function drawSwatch(
    x: number,
    y: number,
    w: number,
    h: number,
    hex: string,
    label: string
  ) {
    const [r, g, b] = hexToRgb(hex);
    doc.setFillColor(r, g, b);
    doc.roundedRect(x, y, w, h, 2, 2, "F");
    doc.setFontSize(6);
    doc.setTextColor(...textLight);
    doc.text(label, x + w / 2, y + h + 4, { align: "center" });
    doc.setFontSize(5);
    doc.setTextColor(...textMuted);
    doc.text(hex, x + w / 2, y + h + 7, { align: "center" });
  }

  // ─── PAGE 1: Cover ───────────────────────
  addBackground();

  // Decorative top bar
  doc.setFillColor(...accent);
  doc.rect(0, 0, pageW, 4, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...textMuted);
  doc.text("PERSONAL COLOR ANALYSIS", pageW / 2, 40, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(36);
  doc.setTextColor(...accent);
  doc.text(data.season.toUpperCase(), pageW / 2, 60, { align: "center" });

  doc.setFontSize(12);
  doc.setTextColor(...textLight);
  doc.text(`Confidence: ${data.confidence}%`, pageW / 2, 72, {
    align: "center",
  });

  // Key features
  let y = 90;
  const features = [
    ["Undertone", data.undertone],
    ["Depth", data.depth],
    ["Chroma", data.chroma],
    ["Korean Tone", data.koreanTone],
  ];
  features.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...accent);
    doc.text(label.toUpperCase(), margin, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...textLight);
    doc.text(String(value), margin + 35, y);
    y += 8;
  });

  // Reasoning
  y += 5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...accent);
  doc.text("Analysis Summary", margin, y);
  y += 6;
  y = addText(data.reasoning, margin, y, contentW, 9, textMuted);

  // Top color swatches preview
  y += 10;
  const previewColors = data.palette.best.slice(0, 12);
  const swatchW = (contentW - 11 * 2) / 12;
  previewColors.forEach((c, i) => {
    drawSwatch(margin + i * (swatchW + 2), y, swatchW, swatchW, c.hex, "");
  });

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(...textMuted);
  doc.text("Generated by Aura Color Analysis", pageW / 2, pageH - 10, {
    align: "center",
  });

  // ─── PAGE 2: Full Color Palette ──────────
  doc.addPage();
  addBackground();
  y = addHeader("Your Color Palette", 25);

  // Best colors
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...textLight);
  doc.text("Colors That Suit You", margin, y);
  y += 8;

  const bestPerRow = 4;
  const bigSwatchW = (contentW - (bestPerRow - 1) * 4) / bestPerRow;
  data.palette.best.forEach((c, i) => {
    const col = i % bestPerRow;
    const row = Math.floor(i / bestPerRow);
    const sx = margin + col * (bigSwatchW + 4);
    const sy = y + row * (bigSwatchW + 16);
    drawSwatch(sx, sy, bigSwatchW, bigSwatchW * 0.6, c.hex, c.name);
    if (c.note) {
      doc.setFontSize(5);
      doc.setTextColor(...textMuted);
      doc.text(c.note, sx + bigSwatchW / 2, sy + bigSwatchW * 0.6 + 10, {
        align: "center",
      });
    }
  });

  y +=
    Math.ceil(data.palette.best.length / bestPerRow) * (bigSwatchW * 0.6 + 16) +
    5;

  // Avoid colors
  if (y > 230) {
    doc.addPage();
    addBackground();
    y = 25;
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(200, 80, 80);
  doc.text("Colors to Avoid", margin, y);
  y += 8;

  data.palette.avoid.forEach((c, i) => {
    const col = i % bestPerRow;
    const row = Math.floor(i / bestPerRow);
    const sx = margin + col * (bigSwatchW + 4);
    const sy = y + row * (bigSwatchW * 0.6 + 14);
    drawSwatch(sx, sy, bigSwatchW, bigSwatchW * 0.4, c.hex, c.name);
  });

  // Metals
  y +=
    Math.ceil(data.palette.avoid.length / bestPerRow) *
      (bigSwatchW * 0.4 + 14) +
    10;
  if (y > 250) {
    doc.addPage();
    addBackground();
    y = 25;
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...accent);
  doc.text("Best Metals", margin, y);
  y += 6;
  y = addText(data.palette.metals.best.join(", "), margin, y, contentW, 10);
  doc.setTextColor(200, 80, 80);
  doc.text("Avoid Metals", margin, y);
  y += 6;
  y = addText(data.palette.metals.avoid.join(", "), margin, y, contentW, 10);

  // ─── PAGE 3: Makeup Guide ────────────────
  doc.addPage();
  addBackground();
  y = addHeader("Makeup Guide", 25);

  const makeupEntries = [
    ["Foundation", data.makeup.foundation],
    ["Blush", data.makeup.blush],
    ["Bronzer", data.makeup.bronzer],
    ["Lips", data.makeup.lips],
    ["Eyes", data.makeup.eyes],
    ["Highlighter", data.makeup.highlighter],
  ];

  makeupEntries.forEach(([label, value]) => {
    if (y > 265) {
      doc.addPage();
      addBackground();
      y = 25;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...accent);
    doc.text(String(label), margin, y);
    y += 5;
    y = addText(String(value || ""), margin, y, contentW, 9, textMuted);
    y += 3;
  });

  // Nail colors
  const nails = data.makeup.nails as
    | { bestColors?: string[]; avoidColors?: string[] }
    | undefined;
  if (nails) {
    if (y > 240) {
      doc.addPage();
      addBackground();
      y = 25;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...accent);
    doc.text("Nail Colors", margin, y);
    y += 6;
    if (nails.bestColors?.length) {
      y = addText(
        "Best: " + nails.bestColors.join(", "),
        margin,
        y,
        contentW,
        9
      );
    }
    if (nails.avoidColors?.length) {
      y = addText(
        "Avoid: " + nails.avoidColors.join(", "),
        margin,
        y,
        contentW,
        9,
        [200, 80, 80]
      );
    }
  }

  // ─── PAGE 4: Wardrobe Guide ──────────────
  doc.addPage();
  addBackground();
  y = addHeader("Wardrobe Guide", 25);

  const wardrobeEntries = [
    ["Best Colors", data.wardrobe.bestColors],
    ["Neutral Anchors", data.wardrobe.neutralAnchors],
    ["Prints & Patterns", data.wardrobe.prints],
    ["Best Fabrics", data.wardrobe.fabrics],
    ["Denim Guide", data.wardrobe.denimGuide],
    ["Avoid", data.wardrobe.avoid],
  ];

  wardrobeEntries.forEach(([label, value]) => {
    if (y > 265) {
      doc.addPage();
      addBackground();
      y = 25;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...accent);
    doc.text(String(label), margin, y);
    y += 5;
    const color: [number, number, number] =
      label === "Avoid" ? [200, 80, 80] : textMuted;
    y = addText(String(value || ""), margin, y, contentW, 9, color);
    y += 3;
  });

  // ─── PAGE 5: Jewelry & Hair ──────────────
  doc.addPage();
  addBackground();
  y = addHeader("Jewelry Guide", 25);

  const jewelryEntries = [
    ["Metals", data.jewelry.metals],
    ["Gemstones", data.jewelry.stones],
    ["Style", data.jewelry.style],
    ["Avoid", data.jewelry.avoid],
  ];
  jewelryEntries.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...accent);
    doc.text(String(label), margin, y);
    y += 5;
    y = addText(String(value || ""), margin, y, contentW, 9, textMuted);
    y += 3;
  });

  y += 10;
  y = addHeader("Hair Color Guide", y);

  const hairEntries = [
    ["Best Highlights", data.hairColor.bestHighlights],
    ["Best Overall", data.hairColor.bestOverall],
    ["Avoid", data.hairColor.avoid],
  ];
  hairEntries.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...accent);
    doc.text(String(label), margin, y);
    y += 5;
    y = addText(String(value || ""), margin, y, contentW, 9, textMuted);
    y += 3;
  });

  // ─── PAGE 6: Celebrities & Korean ────────
  doc.addPage();
  addBackground();
  y = addHeader("Celebrity Color Matches", 25);

  (data.celebrities || []).forEach((celeb) => {
    if (y > 255) {
      doc.addPage();
      addBackground();
      y = 25;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...textLight);
    doc.text(celeb.name, margin, y);
    y += 5;
    y = addText(celeb.why, margin, y, contentW, 9, textMuted);
    y += 4;
  });

  y += 8;
  if (y > 220) {
    doc.addPage();
    addBackground();
    y = 25;
  }
  y = addHeader("Korean Tone Analysis", y);

  if (data.koreanAnalysis) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...accent);
    doc.text(data.koreanAnalysis.tone || "", margin, y);
    y += 8;
    y = addText(
      data.koreanAnalysis.description || "",
      margin,
      y,
      contentW,
      10,
      textLight
    );
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...accent);
    doc.text("K-Beauty Tips", margin, y);
    y += 5;
    y = addText(
      data.koreanAnalysis.kbeautyTips || "",
      margin,
      y,
      contentW,
      9,
      textMuted
    );
  }

  // Footer on last page
  doc.setFontSize(7);
  doc.setTextColor(...textMuted);
  doc.text("Generated by Aura Color Analysis", pageW / 2, pageH - 10, {
    align: "center",
  });

  // Return buffer
  const arrayBuf = doc.output("arraybuffer");
  return Buffer.from(arrayBuf);
}

export function generateWalletCard(data: AnalysisData): Buffer {
  // Credit-card sized: 85.6mm x 53.98mm
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: [53.98, 85.6],
  });
  const w = 85.6;
  const h = 53.98;

  const warm = isWarmSeason(data.season);
  const bgColor: [number, number, number] = warm ? [26, 15, 8] : [8, 15, 26];
  const accentColor: [number, number, number] = warm
    ? [201, 169, 110]
    : [110, 160, 201];
  const textColor: [number, number, number] = warm
    ? [245, 236, 215]
    : [215, 230, 245];

  doc.setFillColor(...bgColor);
  doc.rect(0, 0, w, h, "F");

  // Top accent line
  doc.setFillColor(...accentColor);
  doc.rect(0, 0, w, 2, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(6);
  doc.setTextColor(...accentColor);
  doc.text("COLOR PASSPORT", 4, 7);

  doc.setFontSize(12);
  doc.setTextColor(...textColor);
  doc.text(data.season, 4, 14);

  // Swatches grid (3 rows of 4)
  const swatchSize = 8;
  const gap = 1.5;
  const startX = 4;
  const startY = 18;
  data.palette.best.slice(0, 12).forEach((c, i) => {
    const col = i % 4;
    const row = Math.floor(i / 4);
    const x = startX + col * (swatchSize + gap);
    const y = startY + row * (swatchSize + gap);
    const [r, g, b] = hexToRgb(c.hex);
    doc.setFillColor(r, g, b);
    doc.roundedRect(x, y, swatchSize, swatchSize, 1, 1, "F");
  });

  // Metal recommendation on right side
  doc.setFontSize(5);
  doc.setTextColor(...accentColor);
  doc.text("METALS", 52, 20);
  doc.setFontSize(6);
  doc.setTextColor(...textColor);
  doc.text(data.palette.metals.best.join("\n"), 52, 24);

  // Neutrals
  doc.setFontSize(5);
  doc.setTextColor(...accentColor);
  doc.text("NEUTRALS", 52, 38);
  doc.setFontSize(5);
  doc.setTextColor(...textColor);
  const neutralText = data.palette.neutrals.slice(0, 4).join("\n");
  doc.text(neutralText, 52, 42);

  // Bottom
  doc.setFontSize(4);
  doc.setTextColor(120, 110, 100);
  doc.text("Aura Color Analysis", w / 2, h - 3, { align: "center" });

  const arrayBuf = doc.output("arraybuffer");
  return Buffer.from(arrayBuf);
}
