// Canonical 12-season palettes — keeps results consistent across analyses.
// When a person is classified as Deep Autumn, they always get this Deep Autumn
// palette, regardless of model run-to-run variance.

export type Color = { name: string; hex: string };
export type SeasonPalette = {
  best: (Color & { note: string })[];
  avoid: (Color & { reason: string })[];
  neutrals: Color[];
  metals: { best: string[]; avoid: string[] };
};

const PALETTES: Record<string, SeasonPalette> = {
  "deep autumn": {
    best: [
      { name: "Forest Green", hex: "#228B22", note: "Rich green that grounds your warm depth." },
      { name: "Burgundy", hex: "#800020", note: "Sophisticated wine red — a Deep Autumn signature." },
      { name: "Rust", hex: "#B7410E", note: "Earthy warmth that flatters your golden undertone." },
      { name: "Camel", hex: "#C19A6B", note: "Warm neutral that highlights golden tones." },
      { name: "Mustard", hex: "#C39B26", note: "Vibrant warm yellow that complements your depth." },
      { name: "Terracotta", hex: "#C36651", note: "Sun-baked clay tone that brings out skin warmth." },
      { name: "Pumpkin", hex: "#D85B1F", note: "Vivid orange for statement pieces." },
      { name: "Olive", hex: "#6B7A3A", note: "Earthy green that mirrors your warm depth." },
      { name: "Dark Chocolate", hex: "#4F2F2F", note: "Deep neutral that connects to hair tones." },
      { name: "Warm Plum", hex: "#6B3A5D", note: "Rich purple with warm undertones." },
      { name: "Deep Teal", hex: "#005F60", note: "Warm blue-green for a luxurious accent." },
      { name: "Espresso", hex: "#3D1C02", note: "Profound brown that mirrors your hair depth." },
    ],
    avoid: [
      { name: "Pastel Pink", hex: "#FFD1DC", reason: "Too cool and washed-out for your depth." },
      { name: "Icy Blue", hex: "#A5F2F3", reason: "Cool brightness clashes with your warmth." },
      { name: "Lavender", hex: "#E6E6FA", reason: "Cool and pale — fights your richness." },
      { name: "Pure White", hex: "#FFFFFF", reason: "Stark cool white overwhelms your warm depth." },
      { name: "Mint Green", hex: "#98FF98", reason: "Cool minty tone clashes with your warmth." },
      { name: "Hot Pink", hex: "#FF69B4", reason: "Cool brightness fights your earthy palette." },
    ],
    neutrals: [
      { name: "Espresso", hex: "#3D1C02" },
      { name: "Camel", hex: "#C19A6B" },
      { name: "Dark Chocolate", hex: "#4F2F2F" },
      { name: "Warm Taupe", hex: "#A08070" },
      { name: "Khaki", hex: "#C3B091" },
      { name: "Cream", hex: "#FFFDD0" },
    ],
    metals: { best: ["Yellow Gold", "Bronze", "Copper", "Antique Gold"], avoid: ["Silver", "Platinum", "White Gold"] },
  },

  "true autumn": {
    best: [
      { name: "Pumpkin", hex: "#E8853F", note: "Warm autumn signature." },
      { name: "Mustard", hex: "#C39B26", note: "Earthy yellow that brings out golden warmth." },
      { name: "Olive", hex: "#708238", note: "Classic warm green for True Autumn." },
      { name: "Terracotta", hex: "#C68960", note: "Warm clay tone — perfect skin match." },
      { name: "Cinnamon", hex: "#D2691E", note: "Spicy warmth that complements your undertone." },
      { name: "Tomato Red", hex: "#C04020", note: "Warm red with depth." },
      { name: "Forest Green", hex: "#228B22", note: "Grounded green that suits your warmth." },
      { name: "Camel", hex: "#C19A6B", note: "Warm neutral mainstay." },
      { name: "Bronze", hex: "#CD7F32", note: "Metallic warmth that flatters skin tone." },
      { name: "Warm Beige", hex: "#C8AD7F", note: "Soft warm neutral." },
      { name: "Burnt Orange", hex: "#CC5500", note: "Rich autumn statement color." },
      { name: "Rust", hex: "#B7410E", note: "Earthy red-orange for depth." },
    ],
    avoid: [
      { name: "Icy Pink", hex: "#FAD2E1", reason: "Cool pastel washes you out." },
      { name: "Royal Blue", hex: "#4169E1", reason: "Too cool and bright for your softness." },
      { name: "Pure White", hex: "#FFFFFF", reason: "Stark cool — choose cream instead." },
      { name: "Magenta", hex: "#FF00FF", reason: "Cool brightness fights your warmth." },
      { name: "Black", hex: "#000000", reason: "Too harsh — use chocolate brown for depth." },
      { name: "Light Lavender", hex: "#E6E6FA", reason: "Cool and ashy on warm skin." },
    ],
    neutrals: [
      { name: "Camel", hex: "#C19A6B" },
      { name: "Warm Beige", hex: "#C8AD7F" },
      { name: "Cream", hex: "#FFFDD0" },
      { name: "Chocolate Brown", hex: "#3D1C02" },
      { name: "Khaki", hex: "#C3B091" },
      { name: "Warm Taupe", hex: "#A08070" },
    ],
    metals: { best: ["Yellow Gold", "Bronze", "Copper", "Antique Gold"], avoid: ["Silver", "Platinum", "White Gold"] },
  },

  "soft autumn": {
    best: [
      { name: "Sage Green", hex: "#9CAF88", note: "Muted green that suits your softness." },
      { name: "Salmon Pink", hex: "#E89A87", note: "Warm dusty pink for a soft glow." },
      { name: "Camel", hex: "#C19A6B", note: "Classic warm soft neutral." },
      { name: "Soft Plum", hex: "#8E5A78", note: "Muted purple with warm undertones." },
      { name: "Warm Beige", hex: "#C8AD7F", note: "Quiet warm neutral." },
      { name: "Olive", hex: "#7A8450", note: "Muted earthy green." },
      { name: "Dusty Coral", hex: "#D4877B", note: "Soft, sun-warmed coral." },
      { name: "Mauve", hex: "#B284BE", note: "Cool-warm neutral that flatters Soft Autumn." },
      { name: "Khaki", hex: "#C3B091", note: "Earthy neutral that grounds your softness." },
      { name: "Soft Teal", hex: "#5F9EA0", note: "Muted blue-green accent." },
      { name: "Warm Taupe", hex: "#A08070", note: "Sophisticated warm grey-brown." },
      { name: "Dusty Rose", hex: "#B97C7C", note: "Quiet pink with warm depth." },
    ],
    avoid: [
      { name: "Bright White", hex: "#FFFFFF", reason: "Too stark — choose ivory." },
      { name: "Hot Pink", hex: "#FF69B4", reason: "Brightness overwhelms your softness." },
      { name: "Black", hex: "#000000", reason: "Too harsh — chocolate is gentler." },
      { name: "Electric Blue", hex: "#0080FF", reason: "Saturation fights your muted palette." },
      { name: "Neon Yellow", hex: "#F4FF00", reason: "Vibrancy clashes with subtle warmth." },
      { name: "Royal Purple", hex: "#663399", reason: "Too saturated for Soft Autumn." },
    ],
    neutrals: [
      { name: "Warm Taupe", hex: "#A08070" },
      { name: "Camel", hex: "#C19A6B" },
      { name: "Ivory", hex: "#FFFFF0" },
      { name: "Khaki", hex: "#C3B091" },
      { name: "Cream", hex: "#FFFDD0" },
      { name: "Mushroom", hex: "#B5A59A" },
    ],
    metals: { best: ["Yellow Gold", "Rose Gold", "Antique Gold", "Brushed Bronze"], avoid: ["Silver", "Platinum", "White Gold"] },
  },

  "deep winter": {
    best: [
      { name: "True Black", hex: "#000000", note: "A Deep Winter signature — wear it boldly." },
      { name: "Pure White", hex: "#FFFFFF", note: "Crisp white creates striking contrast." },
      { name: "Crimson", hex: "#DC143C", note: "Cool true red that pops against your depth." },
      { name: "Sapphire Blue", hex: "#0F52BA", note: "Jewel blue that mirrors your clarity." },
      { name: "Emerald", hex: "#0F8C5C", note: "Deep cool green — Deep Winter classic." },
      { name: "Royal Purple", hex: "#5D3B85", note: "Rich cool purple for drama." },
      { name: "Magenta", hex: "#C71585", note: "Cool pink-purple with intensity." },
      { name: "Burgundy", hex: "#5C0A1F", note: "Cool wine that adds richness." },
      { name: "Charcoal", hex: "#36454F", note: "Sophisticated cool grey." },
      { name: "Icy Pink", hex: "#FAD2E1", note: "Cool pale pink for soft contrast." },
      { name: "Pine Green", hex: "#01796F", note: "Cool deep green with character." },
      { name: "Cobalt Blue", hex: "#0047AB", note: "Saturated cool blue — high impact." },
    ],
    avoid: [
      { name: "Beige", hex: "#F5F5DC", reason: "Warm muted tone washes you out." },
      { name: "Pumpkin", hex: "#D85B1F", reason: "Warm orange clashes with cool depth." },
      { name: "Mustard", hex: "#C39B26", reason: "Earthy warmth fights your clarity." },
      { name: "Camel", hex: "#C19A6B", reason: "Warm neutral muddies your sharpness." },
      { name: "Salmon Pink", hex: "#FA8072", reason: "Warm coral fights your cool tone." },
      { name: "Olive", hex: "#708238", reason: "Warm muted green clashes with Deep Winter." },
    ],
    neutrals: [
      { name: "Black", hex: "#000000" },
      { name: "Pure White", hex: "#FFFFFF" },
      { name: "Charcoal", hex: "#36454F" },
      { name: "Navy", hex: "#1C2951" },
      { name: "Pewter", hex: "#8E8E8E" },
      { name: "Icy Grey", hex: "#D3D3D3" },
    ],
    metals: { best: ["Silver", "Platinum", "White Gold", "Pewter"], avoid: ["Yellow Gold", "Bronze", "Copper"] },
  },

  "cool winter": {
    best: [
      { name: "True Red", hex: "#C8102E", note: "Pure cool red — Cool Winter signature." },
      { name: "Royal Blue", hex: "#002FA7", note: "Cool primary blue with intensity." },
      { name: "Emerald", hex: "#0F8C5C", note: "Cool jewel green." },
      { name: "Magenta", hex: "#D6006A", note: "Vibrant cool pink-purple." },
      { name: "Pure White", hex: "#FFFFFF", note: "Crisp clean white." },
      { name: "Black", hex: "#000000", note: "Anchors your cool palette." },
      { name: "Icy Pink", hex: "#FAD2E1", note: "Cool pale pink for softness." },
      { name: "Sapphire", hex: "#0F52BA", note: "Deep clear blue." },
      { name: "Burgundy", hex: "#5C0A1F", note: "Cool deep red wine." },
      { name: "Lavender", hex: "#9683EC", note: "Cool clear purple." },
      { name: "Charcoal", hex: "#36454F", note: "Cool sophisticated grey." },
      { name: "Lemon Ice", hex: "#FFFACD", note: "Pale cool yellow." },
    ],
    avoid: [
      { name: "Pumpkin", hex: "#D85B1F", reason: "Warm orange fights your coolness." },
      { name: "Camel", hex: "#C19A6B", reason: "Warm neutral muddies you." },
      { name: "Olive", hex: "#708238", reason: "Earthy warm tone clashes." },
      { name: "Beige", hex: "#F5F5DC", reason: "Warm and washed out." },
      { name: "Coral", hex: "#FF7F50", reason: "Too warm and orange." },
      { name: "Mustard", hex: "#C39B26", reason: "Warm yellow fights your tone." },
    ],
    neutrals: [
      { name: "Black", hex: "#000000" },
      { name: "Pure White", hex: "#FFFFFF" },
      { name: "Navy", hex: "#1C2951" },
      { name: "Cool Grey", hex: "#9E9E9E" },
      { name: "Charcoal", hex: "#36454F" },
      { name: "Soft White", hex: "#F8F8FF" },
    ],
    metals: { best: ["Silver", "Platinum", "White Gold"], avoid: ["Yellow Gold", "Bronze", "Copper"] },
  },

  "bright winter": {
    best: [
      { name: "Hot Pink", hex: "#FF1493", note: "Saturated cool pink — Bright Winter signature." },
      { name: "Electric Blue", hex: "#0080FF", note: "Vivid clear blue." },
      { name: "True Red", hex: "#E40046", note: "Bright clear red." },
      { name: "Emerald", hex: "#00A86B", note: "Vivid jewel green." },
      { name: "Royal Purple", hex: "#5D3B85", note: "Rich saturated purple." },
      { name: "Pure White", hex: "#FFFFFF", note: "Crisp bright white." },
      { name: "Black", hex: "#000000", note: "Sharp contrast anchor." },
      { name: "Lemon Yellow", hex: "#FFF200", note: "Bright clear yellow." },
      { name: "Turquoise", hex: "#30D5C8", note: "Clear blue-green statement." },
      { name: "Magenta", hex: "#FF00FF", note: "Saturated pink-purple." },
      { name: "Cobalt Blue", hex: "#0047AB", note: "Deep saturated blue." },
      { name: "Icy Mint", hex: "#9FFFCB", note: "Cool bright green." },
    ],
    avoid: [
      { name: "Beige", hex: "#F5F5DC", reason: "Muted warm tone dulls your brightness." },
      { name: "Olive", hex: "#708238", reason: "Earthy muted green clashes." },
      { name: "Camel", hex: "#C19A6B", reason: "Warm neutral fights your clarity." },
      { name: "Dusty Rose", hex: "#B97C7C", reason: "Muted warm tone — too soft." },
      { name: "Khaki", hex: "#C3B091", reason: "Muted warm — fights brightness." },
      { name: "Mustard", hex: "#C39B26", reason: "Warm earthy tone clashes." },
    ],
    neutrals: [
      { name: "Black", hex: "#000000" },
      { name: "Pure White", hex: "#FFFFFF" },
      { name: "Charcoal", hex: "#36454F" },
      { name: "Navy", hex: "#1C2951" },
      { name: "Bright Grey", hex: "#A0A0A0" },
      { name: "Icy White", hex: "#F8F8FF" },
    ],
    metals: { best: ["Silver", "Platinum", "White Gold"], avoid: ["Bronze", "Copper", "Antique Gold"] },
  },

  "light summer": {
    best: [
      { name: "Soft Pink", hex: "#F4A6BC", note: "Cool delicate pink for Light Summer." },
      { name: "Powder Blue", hex: "#B0E0E6", note: "Quintessential cool soft blue." },
      { name: "Lavender", hex: "#C8B6E0", note: "Cool soft purple — Light Summer favorite." },
      { name: "Soft Mint", hex: "#A8DCC0", note: "Cool gentle green." },
      { name: "Light Periwinkle", hex: "#B6BCDB", note: "Soft cool blue-purple." },
      { name: "Soft Coral", hex: "#F1A6A2", note: "Gentle cool-warm pink." },
      { name: "Pearl White", hex: "#F8F8FF", note: "Soft cool white." },
      { name: "Pale Aqua", hex: "#B5DEE5", note: "Light cool blue-green." },
      { name: "Soft Lemon", hex: "#FBF1B5", note: "Pale cool yellow." },
      { name: "Champagne", hex: "#F4E4C7", note: "Cool soft neutral with warmth." },
      { name: "Light Mauve", hex: "#D2B6D5", note: "Cool delicate purple-pink." },
      { name: "Dusty Blue", hex: "#9DBED1", note: "Muted cool blue accent." },
    ],
    avoid: [
      { name: "Black", hex: "#000000", reason: "Too harsh and dark for your softness." },
      { name: "Pumpkin", hex: "#D85B1F", reason: "Warm vivid orange fights cool softness." },
      { name: "Mustard", hex: "#C39B26", reason: "Warm earthy — clashes with your cool." },
      { name: "Hot Pink", hex: "#FF1493", reason: "Too saturated for your delicate palette." },
      { name: "Burgundy", hex: "#800020", reason: "Too dark — choose dusty rose instead." },
      { name: "Olive", hex: "#708238", reason: "Earthy warm — washes you out." },
    ],
    neutrals: [
      { name: "Pearl White", hex: "#F8F8FF" },
      { name: "Light Grey", hex: "#D3D3D3" },
      { name: "Soft Navy", hex: "#3D4A6B" },
      { name: "Cool Beige", hex: "#C8B9A2" },
      { name: "Champagne", hex: "#F4E4C7" },
      { name: "Dove Grey", hex: "#B6B6B4" },
    ],
    metals: { best: ["Silver", "White Gold", "Rose Gold", "Platinum"], avoid: ["Yellow Gold", "Bronze", "Copper"] },
  },

  "true summer": {
    best: [
      { name: "Rose Pink", hex: "#D87093", note: "Cool dusty pink — True Summer staple." },
      { name: "Steel Blue", hex: "#4682B4", note: "Cool sophisticated blue." },
      { name: "Soft Plum", hex: "#7B5286", note: "Cool muted purple." },
      { name: "Sage Green", hex: "#9CAF88", note: "Cool muted green." },
      { name: "Burgundy", hex: "#722F37", note: "Cool muted wine." },
      { name: "Cool Grey", hex: "#9CA0A6", note: "Sophisticated neutral." },
      { name: "Periwinkle", hex: "#8FAFE5", note: "Cool clear blue-purple." },
      { name: "Dusty Rose", hex: "#C08081", note: "Soft cool pink." },
      { name: "Powder Blue", hex: "#B0E0E6", note: "Cool light blue." },
      { name: "Mauve", hex: "#9C7B8C", note: "Cool muted purple-pink." },
      { name: "Soft White", hex: "#F8F8FF", note: "Clean cool white." },
      { name: "Navy", hex: "#1C2951", note: "Cool deep neutral anchor." },
    ],
    avoid: [
      { name: "Pumpkin", hex: "#D85B1F", reason: "Warm orange fights your cool tone." },
      { name: "Mustard", hex: "#C39B26", reason: "Warm earthy yellow clashes." },
      { name: "Camel", hex: "#C19A6B", reason: "Warm neutral muddies you." },
      { name: "Black", hex: "#000000", reason: "Too harsh — choose navy." },
      { name: "Bright Coral", hex: "#FF7F50", reason: "Too warm and saturated." },
      { name: "Olive", hex: "#708238", reason: "Warm earthy — fights your softness." },
    ],
    neutrals: [
      { name: "Soft Navy", hex: "#3D4A6B" },
      { name: "Cool Grey", hex: "#9E9E9E" },
      { name: "Soft White", hex: "#F8F8FF" },
      { name: "Cool Beige", hex: "#C8B9A2" },
      { name: "Pewter", hex: "#8E8E8E" },
      { name: "Dove Grey", hex: "#B6B6B4" },
    ],
    metals: { best: ["Silver", "White Gold", "Platinum"], avoid: ["Yellow Gold", "Bronze", "Copper"] },
  },

  "soft summer": {
    best: [
      { name: "Dusty Rose", hex: "#B97C7C", note: "Quiet cool pink — Soft Summer staple." },
      { name: "Sage Green", hex: "#9CAF88", note: "Muted cool-warm green." },
      { name: "Soft Plum", hex: "#7B5286", note: "Cool muted purple." },
      { name: "Slate Blue", hex: "#6A7B8C", note: "Muted cool blue." },
      { name: "Mauve", hex: "#9C7B8C", note: "Cool muted purple-pink." },
      { name: "Cool Taupe", hex: "#8B7E74", note: "Sophisticated muted neutral." },
      { name: "Powder Blue", hex: "#B0E0E6", note: "Soft cool blue." },
      { name: "Soft Teal", hex: "#5F9EA0", note: "Muted blue-green accent." },
      { name: "Cocoa", hex: "#7B5C4F", note: "Cool muted brown." },
      { name: "Dusty Lavender", hex: "#A89DBA", note: "Cool soft purple." },
      { name: "Soft Burgundy", hex: "#8C5566", note: "Muted cool wine." },
      { name: "Cool Grey", hex: "#9E9E9E", note: "Versatile sophisticated neutral." },
    ],
    avoid: [
      { name: "Pumpkin", hex: "#D85B1F", reason: "Warm vibrant — fights your softness." },
      { name: "Hot Pink", hex: "#FF1493", reason: "Too saturated for Soft Summer." },
      { name: "Black", hex: "#000000", reason: "Too harsh — choose deep grey." },
      { name: "Mustard", hex: "#C39B26", reason: "Warm earthy yellow clashes." },
      { name: "Pure White", hex: "#FFFFFF", reason: "Too stark — choose soft white." },
      { name: "Royal Blue", hex: "#4169E1", reason: "Too saturated for your muted palette." },
    ],
    neutrals: [
      { name: "Cool Taupe", hex: "#8B7E74" },
      { name: "Soft Navy", hex: "#3D4A6B" },
      { name: "Cool Grey", hex: "#9E9E9E" },
      { name: "Soft White", hex: "#F8F8FF" },
      { name: "Mushroom", hex: "#B5A59A" },
      { name: "Pewter", hex: "#8E8E8E" },
    ],
    metals: { best: ["Silver", "White Gold", "Brushed Pewter"], avoid: ["Yellow Gold", "Bronze", "Copper"] },
  },

  "light spring": {
    best: [
      { name: "Peach", hex: "#FFB59B", note: "Warm soft peach — Light Spring signature." },
      { name: "Coral", hex: "#FFA07A", note: "Warm light coral." },
      { name: "Light Aqua", hex: "#A5DCE3", note: "Clear warm-cool blue-green." },
      { name: "Soft Yellow", hex: "#FAEBA8", note: "Warm light yellow." },
      { name: "Mint", hex: "#A6E5C2", note: "Clear warm-cool green." },
      { name: "Light Pink", hex: "#F4B7C2", note: "Warm soft pink." },
      { name: "Periwinkle", hex: "#A6C0F0", note: "Warm clear blue-purple." },
      { name: "Camel", hex: "#D9B68A", note: "Warm light neutral." },
      { name: "Light Coral Red", hex: "#FF8E76", note: "Vivid warm pink-red." },
      { name: "Apricot", hex: "#FFCB94", note: "Warm soft orange." },
      { name: "Ivory", hex: "#FFFFF0", note: "Warm clean white." },
      { name: "Soft Turquoise", hex: "#7AD0CC", note: "Clear warm green-blue." },
    ],
    avoid: [
      { name: "Black", hex: "#000000", reason: "Too harsh and dark for your softness." },
      { name: "Burgundy", hex: "#800020", reason: "Too dark — fights your lightness." },
      { name: "Pure White", hex: "#FFFFFF", reason: "Too stark — choose ivory." },
      { name: "Charcoal", hex: "#36454F", reason: "Too dark and cool." },
      { name: "Hot Pink", hex: "#FF1493", reason: "Too saturated for your softness." },
      { name: "Olive", hex: "#708238", reason: "Too earthy and muted." },
    ],
    neutrals: [
      { name: "Ivory", hex: "#FFFFF0" },
      { name: "Camel", hex: "#D9B68A" },
      { name: "Warm Beige", hex: "#E0CFA9" },
      { name: "Soft Navy", hex: "#3D4A6B" },
      { name: "Cream", hex: "#FFFDD0" },
      { name: "Light Grey", hex: "#D3D3D3" },
    ],
    metals: { best: ["Yellow Gold", "Rose Gold", "Champagne Gold"], avoid: ["Silver", "Platinum"] },
  },

  "true spring": {
    best: [
      { name: "Coral", hex: "#FF7F50", note: "Warm clear coral — True Spring signature." },
      { name: "Warm Yellow", hex: "#FFD13F", note: "Bright warm yellow." },
      { name: "Tomato Red", hex: "#E1493B", note: "Warm clear red." },
      { name: "Turquoise", hex: "#3CCDC8", note: "Clear warm blue-green." },
      { name: "Bright Green", hex: "#5BC23A", note: "Vivid warm green." },
      { name: "Periwinkle", hex: "#7592D3", note: "Warm clear blue-purple." },
      { name: "Peach", hex: "#FFB05E", note: "Warm vibrant peach." },
      { name: "Camel", hex: "#D9B68A", note: "Warm clear neutral." },
      { name: "Hot Pink", hex: "#FF6FA0", note: "Warm bright pink." },
      { name: "Cobalt Blue", hex: "#1F58D8", note: "Warm clear blue." },
      { name: "Apricot", hex: "#FF9647", note: "Warm vivid orange." },
      { name: "Ivory", hex: "#FFFFF0", note: "Warm clean white." },
    ],
    avoid: [
      { name: "Black", hex: "#000000", reason: "Too harsh for your warm clarity." },
      { name: "Burgundy", hex: "#800020", reason: "Too dark and cool-leaning." },
      { name: "Mauve", hex: "#9C7B8C", reason: "Muted cool tone fights your warmth." },
      { name: "Charcoal", hex: "#36454F", reason: "Too cool and heavy." },
      { name: "Cool Grey", hex: "#9E9E9E", reason: "Lacks warmth." },
      { name: "Dusty Pink", hex: "#B97C7C", reason: "Too muted for your clarity." },
    ],
    neutrals: [
      { name: "Ivory", hex: "#FFFFF0" },
      { name: "Camel", hex: "#D9B68A" },
      { name: "Warm Beige", hex: "#E0CFA9" },
      { name: "Cream", hex: "#FFFDD0" },
      { name: "Tan", hex: "#D2B48C" },
      { name: "Soft White", hex: "#F8F8FF" },
    ],
    metals: { best: ["Yellow Gold", "Rose Gold", "Bronze"], avoid: ["Silver", "Platinum", "White Gold"] },
  },

  "bright spring": {
    best: [
      { name: "Bright Coral", hex: "#FF6B5B", note: "Vivid warm coral — Bright Spring signature." },
      { name: "Warm Pink", hex: "#FF4F8B", note: "Saturated warm pink." },
      { name: "Bright Turquoise", hex: "#1FCBC8", note: "Clear warm blue-green." },
      { name: "Lemon Yellow", hex: "#FFE63A", note: "Bright clear yellow." },
      { name: "Apple Green", hex: "#8DD83D", note: "Vivid warm green." },
      { name: "Periwinkle", hex: "#6E83E0", note: "Bright clear blue-purple." },
      { name: "Tomato Red", hex: "#E1493B", note: "Saturated warm red." },
      { name: "Royal Blue", hex: "#1F58D8", note: "Clear warm blue." },
      { name: "Magenta", hex: "#E0006A", note: "Vivid warm pink." },
      { name: "Bright Orange", hex: "#FF8C24", note: "Saturated warm orange." },
      { name: "Ivory", hex: "#FFFFF0", note: "Warm clean white." },
      { name: "Camel", hex: "#D9B68A", note: "Warm clear neutral." },
    ],
    avoid: [
      { name: "Burgundy", hex: "#800020", reason: "Too dark and muted." },
      { name: "Olive", hex: "#708238", reason: "Earthy muted — fights your clarity." },
      { name: "Black", hex: "#000000", reason: "Too harsh for your warmth." },
      { name: "Dusty Rose", hex: "#B97C7C", reason: "Too muted for your brightness." },
      { name: "Charcoal", hex: "#36454F", reason: "Too dark and cool." },
      { name: "Sage Green", hex: "#9CAF88", reason: "Muted — clashes with brightness." },
    ],
    neutrals: [
      { name: "Ivory", hex: "#FFFFF0" },
      { name: "Camel", hex: "#D9B68A" },
      { name: "Cream", hex: "#FFFDD0" },
      { name: "Tan", hex: "#D2B48C" },
      { name: "Warm Beige", hex: "#E0CFA9" },
      { name: "Soft White", hex: "#F8F8FF" },
    ],
    metals: { best: ["Yellow Gold", "Rose Gold"], avoid: ["Silver", "Platinum", "Pewter"] },
  },
};

// Aliases — different prompt wording maps to the same canonical key
const ALIASES: Record<string, string> = {
  "warm autumn": "true autumn",
  "warm spring": "true spring",
  "warm summer": "true summer",
  "cool summer": "true summer",
  "dark autumn": "deep autumn",
  "dark winter": "deep winter",
  "clear winter": "bright winter",
  "clear spring": "bright spring",
  "muted autumn": "soft autumn",
  "muted summer": "soft summer",
};

export function getCanonicalPalette(season: string | undefined): SeasonPalette | null {
  if (!season) return null;
  const key = season.toLowerCase().trim();
  if (PALETTES[key]) return PALETTES[key];
  if (ALIASES[key] && PALETTES[ALIASES[key]]) return PALETTES[ALIASES[key]];
  return null;
}
